{% set name = "pycryptodomex" %}
{% set version = "3.21.0" %}
{% set sha256 = "222d0bd05381dd25c32dd6065c071ebf084212ab79bab4599ba9e6a3e0009e6c" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    # ctypes.util.find_library() isn't CONDA_PREFIX aware :'(
    # https://github.com/ContinuumIO/anaconda-issues/issues/1716
    - patches/0001-Make-load_lib-CONDA_PREFIX-aware.patch  # [unix]

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv --no-build-isolation

requirements:
  build:
    - {{ compiler('c') }}
    - patch       # [not win]
  host:
    - python
    - pip
    - setuptools
    - wheel
    - gmp   # [not win]
  run:
    - python

test:
  imports:
    - Cryptodome
    - Cryptodome.Cipher
    - Cryptodome.Hash
    - Cryptodome.IO
    - Cryptodome.Math
    - Cryptodome.Protocol
    - Cryptodome.PublicKey
    - Cryptodome.Random
    - Cryptodome.SelfTest
    - Cryptodome.SelfTest.Cipher
    - Cryptodome.SelfTest.Hash
    - Cryptodome.SelfTest.IO
    - Cryptodome.SelfTest.Math
    - Cryptodome.SelfTest.Protocol
    - Cryptodome.SelfTest.PublicKey
    - Cryptodome.SelfTest.Random
    - Cryptodome.SelfTest.Signature
    - Cryptodome.SelfTest.Util
    - Cryptodome.Signature
    - Cryptodome.Util
  requires:
    - psutil
    - pip
  commands:
    - pip check

about:
  home: https://www.pycryptodome.org
  license: Public Domain/BSD 2-Clause
  license_file: LICENSE.rst
  license_family: Other
  summary: Cryptographic library for Python
  description: |
    PyCryptodome is a self-contained Python package of low-level cryptographic
    primitives.
  doc_url: https://www.pycryptodome.org/en/latest/
  dev_url: https://github.com/Legrandin/pycryptodome

extra:
  recipe-maintainers:
    - nehaljwani
