travis:
  secure:
    BINSTAR_TOKEN: VMdjC0l8yXNuXFis+R4Ugw2FW8ErwAXZgDa1ymd0KY9xyAArWhNLHH2868jJZ42IyQmL3Hz1aEbsOj7+lNpV9LsUcX191ajoTztGq5JgTcgVeEd1Zaeva0Mgvgh3GVajxydx+ZN/ODPibmmshUcAy9Dg7TGw+Bz44hcozdCO6Hx8UUlrVXIx0h8bA5GbmkXOAz+A0z5SaP+sEKB4j3I4HkvxlhqRTGMD6feuhZNDvgoLlXb9HYZKT6dgI15kV6r3eBazYXyArUt4qKlmZNV69/FDHkabdUuAcMBzNP0S+FBeKqTSrExZZsm+wcY4Gu9TPjzITKN3Pehd3mlLbSkglgwRm5EbXW/bvtPhESQ7jFQok1rNDlA0JeYSUeTdrLPIZJFchqRTlUzDwFPU3ysL1bPxOTJ3ET6h5rZd4a9Qz4MH9QR7wsUT/jnEuW4Duq5sDPK03lCx4oGpBwBj2horXrZ52nigl+LoTM43XgPZ7X9OTahmLH34HEqMFirE1GDBZPiXXGZbW3Kg41dFqn7KC7XdBmKgEe4Vt9crtEeJ8WvAZvfwyvrb7fY/YB7nehel2PgVuqoc6MbjicRugEGUaiq3VIwd0H9kZcdiH74nU4IBBp0wmbURLxBODZlQrQmwnDXYaaONG8J46xeoM5U0txGIttIrXIQjWnFrLyYp00g=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
