travis:
  secure:
    BINSTAR_TOKEN: j6ed6IpJ911XRhyeRO0AKZAuSuTWBotHAV3x41+WE7Rgx8kI+O4+cl3L6ZfQHgHO3Ym52GxevP0npxDDeR4EIaoG9s3jf+hA3ldPDjcE6cxDl9raYAn8TKg1WgZdwXB9P+pykR8a8rr39JcCJCbnpiZILQ+zpnEjka05fn7qDIo/JNqXz8eN1CY0Mf+VIbOXva6YHqfCpTxsNd3vxtZMxgZza40idnxvGjq1ugJaM/iruNRFr3jw3Ju8ePz3jnnj57cedPq/flQwMWRzJsDsqokbLv0SD7xJDJYTTs9JTFp5gMGoyxrAJEy7OoDiwTOQeGoTUgV6AYqHx7dYQpHzRA7c0CWMA0UEeISvTx4pgDsqMHzLOV36+jA/IjgOJsD5UL5ZwtUpWfnzcnyNAgVd/gzWioA7oLEidSRdWdYdrYfYPCfodftGh9psLCYJpQSbbEUFZrjoJ3cbYdqMG+5h2n6epXyVnAS6xGtyBnu5tdQnHbJv1FwQMXAZIao4BTxDmRv0MnDqOHe3BIlKi+XWjO2guYIS1MJqnqHLnXN3X7bAW+rxejGCXkdSLkGzkZT+SGM5khP3xgYMjevE8q+QiZrODxSUSEA0bbUcq7f2fefOHwbdiMzho7YaifsBDM4lL1hbKCUOqOXJ9QMgEgeGz+t8YTVpyekexAMcD+YM/+E=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
